const candidateTypes = {
    GET_DATA: 'CANDIDATE USER TYPE GET DATA',
    GET_DATA_STATUS: 'CANDIDATE USER TYPE GET DATA STATUS',
    GET_DATA_MEDIA: 'CANDIDATE USER TYPE GET DATA MEDIA',
    GET_DATA_TAB: 'CANDIDATE USER TYPE GET DATA TAB',
    ADDNEW: 'CANDIDATE ADD NEW DATA',
    REMOVE_DATA: 'CANDIDATE REMOVE DATA',
    SUBMIT: 'CANDIDATE SUBMIT DATA',
    CHANGE_DATA: 'CANDIDATE CHANGE DATA',
    CHANGE_DATA_TAB: 'CANDIDATE CHANGE DATA TAB',
    RESET_FORM: 'CANDIDATE RESET DATA',
    
  }
  export default candidateTypes